# PostgreSQL Exporter Helm Values

# Image configuration
image:
  tag: "v0.12.0"

# Datasource configuration
config:
  datasource:
    host: "postgresql.database-monitoring.svc.cluster.local"
    userSecret:
      name: postgresql-secret
      key: POSTGRES_USER
    passwordSecret:
      name: postgresql-secret
      key: POSTGRES_PASSWORD
    port: "5432"
    # database: "postgres"  

serviceMonitor:
  enabled: true
  interval: 30s
  scrapeTimeout: 10s
  labels:
    release: prometheus

# # Explicitly set the DATA_SOURCE_NAME environment variable
# extraEnvs:
#   - name: DATA_SOURCE_NAME
#     value: "postgresql://postgres:password123@postgresql.database-monitoring.svc.cluster.local:5432/postgres?sslmode=disable"
