apiVersion: v1
kind: Service
metadata:
  name: postgresql
  namespace: database-monitoring
  labels:
    app: postgresql
spec:
  ports:
    - port: 5432
      targetPort: 5432
  selector:
    app: postgresql